postgres:
  build: postgres-docker
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"

elasticsearch:
  build: elasticsearch-docker
  ports:
    - "9200:9200"
    - "9300:9300"

cassandra:
  image: cassandra:latest
  ports:
    - "7000:7000"
    - "7001:7001"
    - "9160:9160"
    - "9042:9042"
    - "7199:7199"

setupcassandra:
  build: cassandra-docker
  links:
    - cassandra
  command: bash -c "sleep 20 && echo Creating keyspace test && cqlsh cassandra -f init.cql && sleep infinity"

zookeeper:
  image: jplock/zookeeper:3.4.6
  ports:
    - "2181:2181"
    - "8080:8080"

datomic:
  build: datomic-docker
  environment:
    - TARGET_HOST $TARGET_HOST
  ports:
    - "4334:4334"
    - "4335:4335"
    - "4336:4336"

dynamo:
  image: deangiberson/aws-dynamodb-local
  ports:
    - "8000:8000"

# hive:
#   image: inmobi/docker-hive:latest
#   ports:
#     - "10000:10000"
#     - "9083:9083"
